dist: xenial
language: go
sudo: false
go:
- 1.11.x
env:
  global:
  - GOARCH=amd64
before_install:
- "./prepare.sh"
install:
- 
script:
- "./build.sh"
- "./package.sh"
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: j+/dOwkRS5wo5h66i4PVK+CPbOUJz5KXFC50FoMFaxcuC8P7PzGdTM+AKREBiobbejpy78DW5bP8JfQGR8T/bHH/+JPRG2XDCdDPnyUG7YXJTtch+19dCCDPDxo/qS2n/lJohzjwjA3FaPsGDJtLxf561xUsIXHt9Kuz4G2ObJogmTFs1Q9Vc5KVOWqhiwqPbvYAN4/rE5rXy7HrdqpBLAO+n+cMclR8M6gr94L9s0IoTg9P2LHriNsL5jX261xQ4fJVVzADQIlrgF5e9K+a4fwtBD8wnnrHd2ZwcwRxKuCdFajl9kUiMB3E1sOKXvnH3sIgtjUrJYHGzL7cR7sXbHCAO8dkPX6OAvis0TPntVNva+rRZDXC92jsK3l9VET9nIwoorZCXfIUFyEk/XAWn+OLvCxORpP0/TkZtXMjBHxdoDKIDl32T7gyXXB538Tl56eRV8Rx2Z8klOW4pjkD60MlLMq9Z+CAUeD+zg4Lo8KOnUb2eCtLWPgadb5TvcgGqnejb9vTIYntzUbxPR5tNGKjNWhpis57r8MJwS9n3zP8TpfV23SWYEiKQU0oiYh1oM3WQw2YL2lFY0oHCI7/+ZJBovTRU81GnMSSXE6KdISlwbk6Un/fJw1uhT+4BW9bY/quSHhZd0Opl+tfCA4OXD9N2GzJci2WRTTPkpC/yPY=
  file: dist/m3-ext*
  on:
    repo: dhnt/m3-ext
    tags: true
